### ISSUE TITLE
cfn-flip takes a json and outputs a json...

### ISSUE THREAD

**Issue by shadycuz** [awslabs/aws-cfn-template-flip#27] opened 2017-09-22 21:31 UTC
This might be because I'm on WLS (Windows Ubuntu). I noticed other people said they had success running it on WLS. 
```
levi@La-Tower:/mnt/c/linux/repos/rho-cf-modules/galaxy$ head -50 galaxy.json
{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Description" : "AWS CloudFormation stack that bring up a cfncluster with galaxy docker running on master.",
  "Metadata" : {
    "AWS::CloudFormation::Interface" : {
      "ParameterGroups" : [
        {
          "Label" : {
            "default" : "Cluster - Basic Setting"
          },
          "Parameters" : [
            "KeyName",
            "MasterInstanceType",
            "ComputeInstanceType",
            "BaseOS",
            "Scheduler",
            "Environment",
            "DevopsBucket"
          ]
        },
        {
          "Label" : {
            "default" : "EBS - Basic Settings"
          },
          "Parameters" : [
            "VolumeSize"
          ]
        },
        {
          "Label" : {
            "default" : "Network - Advanced Settings"
          },
          "Parameters" : [
            "AccessFrom",
            "ComputeSubnetId",
            "ComputeSubnetCidr",
            "UsePublicIps",
            "AdditionalSG",
            "VPCSecurityGroupId"
          ]
        },
        {
          "Label" : {
            "default" : "Cluster - Advanced Setting"
          },
          "Parameters" : [
            "InitialQueueSize",
            "ComputeWaitConditionCount",
            "MaxQueueSize",
            "SpotPrice",
levi@La-Tower:/mnt/c/linux/repos/rho-cf-modules/galaxy$ cfn
cfncluster  cfn-flip
levi@La-Tower:/mnt/c/linux/repos/rho-cf-modules/galaxy$ cfn-flip galaxy.json galaxy.yml
levi@La-Tower:/mnt/c/linux/repos/rho-cf-modules/galaxy$ head -50 galaxy.yml
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "AWS CloudFormation stack that bring up a cfncluster with galaxy docker running on master.",
    "Metadata": {
        "AWS::CloudFormation::Interface": {
            "ParameterGroups": [
                {
                    "Label": {
                        "default": "Cluster - Basic Setting"
                    },
                    "Parameters": [
                        "KeyName",
                        "MasterInstanceType",
                        "ComputeInstanceType",
                        "BaseOS",
                        "Scheduler",
                        "Environment",
                        "DevopsBucket"
                    ]
                },
                {
                    "Label": {
                        "default": "EBS - Basic Settings"
                    },
                    "Parameters": [
                        "VolumeSize"
                    ]
                },
                {
                    "Label": {
                        "default": "Network - Advanced Settings"
                    },
                    "Parameters": [
                        "AccessFrom",
                        "ComputeSubnetId",
                        "ComputeSubnetCidr",
                        "UsePublicIps",
                        "AdditionalSG",
                        "VPCSecurityGroupId"
                    ]
                },
                {
                    "Label": {
                        "default": "Cluster - Advanced Setting"
                    },
                    "Parameters": [
                        "InitialQueueSize",
                        "ComputeWaitConditionCount",
                        "MaxQueueSize",
                        "SpotPrice",
```

Am I doing something wrong?

**Comment by stilvoid** [comment] 2017-10-09 11:38
So this is very likely down to a bug that I don't yet know how to solve.

Basically, the autodetection of whether the input is JSON or YAML is done by first seeing if it can parse the input as JSON. If that fails, it tries parsing as YAML.

The JSON parser is very strict so an extra comma can throw it out and it gets parsed as YAML. JSON (even JSON with extraneous commas) is valid YAML so cfn-flip is doing the "correct" thing in converting what it sees as YAML into JSON.

I'd recommend running your input through a JSON linter first such as the one at https://jsonlint.com/

**Comment by stilvoid** [comment] 2017-11-08 23:21
I'm going to close this for now as it's technically not a bug.

**Closed by stilvoid** 2017-11-08 23:21 UTC
